name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show release tag
        run: |
          echo "A new release was published!"
          echo "Tag name: ${{ github.event.release.tag_name }}"

      - name: Simulate a build process
        run: |
          echo "Simulating code build..."
          echo "Pretend we compile code here (e.g., create .dll or .jar)"
